<%@ page contentType="text/html" pageEncoding="UTF-8" %>
<%@ page import = "java.sql.*" %>


<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Database SQL Load</title>
    </head>
    <style>
        .error {
            color: red;
        }
        pre {
            color: green;
        }
    </style>
    <body>
        <h2>Database SQL Load</h2>
        <%
            /* How to customize:
             * 1. Update the database name on dbname.
             * 2. Create the list of tables, under tablenames[].
             * 3. Create the list of table definition, under tables[].
             * 4. Create the data into the above table, under data[]. 
             * 
             * If there is any problem, it will exit at the very first error.
             */
            String dbname = "homework1";
            String schema = "ROOT";
            Class.forName("org.apache.derby.jdbc.ClientDriver");
            /* this will generate database if not exist */
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/" + dbname, "root", "root");
            Statement stmt = con.createStatement();
            
            /* inserting data */
            /* you have to exclude the id autogenerated from the list of columns if you have use it. */
            String data[] = new String[]{
                "INSERT INTO " + schema + ".HABITACIO VALUES (NEXT VALUE FOR COMMENT_GEN, 'descripcio habitacio 1', 'C/Mossen martí 33 3r 3a', 'Valls', TipusHabitacio.SIMPLE, 500.10,requeriment????? ,FOREIGN KEY(ID) REFERENCES LLOGATER(ID)???)",
                "INSERT INTO " + schema + ".HABITACIO VALUES (NEXT VALUE FOR COMMENT_GEN, 'descripcio habitacio 2', 'C/Major 72', 'Montferri', TipusHabitacio.DOBLE, 400, requeriment????? ,FOREIGN KEY(ID) REFERENCES LLOGATER(ID)???)",
                "INSERT INTO " + schema + ".HABITACIO VALUES (NEXT VALUE FOR COMMENT_GEN, 'descripcio habitacio 3', 'Avda. Paisos Catalans 12', 'Reus', TipusHabitacio.MOBLADA, 600.10, requeriment????? ,FOREIGN KEY(ID) REFERENCES LLOGATER(ID)???)",
                "INSERT INTO " + schema + ".HABITACIO VALUES (NEXT VALUE FOR COMMENT_GEN, 'descripcio habitacio 4', 'Rambla nova 5', 'Tarragona', TipusHabitacio.INTERIOR, 100.22,requeriment?????  ,FOREIGN KEY(ID) REFERENCES LLOGATER(ID)???)",
                "INSERT INTO " + schema + ".HABITACIO VALUES (NEXT VALUE FOR COMMENT_GEN, 'descripcio habitacio 5', 'C/Rafael de Casanova', 'Valls', TipusHabitacio.EXTERIOR, 120.33, requeriment????? ,FOREIGN KEY(ID) REFERENCES LLOGATER(ID)???)",
                "INSERT INTO " + schema + ".HABITACIO VALUES (NEXT VALUE FOR COMMENT_GEN, 'descripcio habitacio 6', 'Avda. Catalunya 2', 'Vallmoll', TipusHabitacio.SIMPLE, 200.10, requeriment?????  ,FOREIGN KEY(ID) REFERENCES LLOGATER(ID)???)",
                
                "INSERT INTO " + schema + ".LLOGATER VALUES (NEXT VALUE FOR COMMENT_GEN, infollogater???, TRUE, nse com fotreli la habitacio xd)",
                "INSERT INTO " + schema + ".LLOGATER VALUES (NEXT VALUE FOR COMMENT_GEN, infollogater???, TRUE, nse com fotreli la habitacio xd)",
                "INSERT INTO " + schema + ".LLOGATER VALUES (NEXT VALUE FOR COMMENT_GEN, infollogater???, TRUE, nse com fotreli la habitacio xd)",
                "INSERT INTO " + schema + ".LLOGATER VALUES (NEXT VALUE FOR COMMENT_GEN, infollogater???, TRUE, nse com fotreli la habitacio xd)",
                "INSERT INTO " + schema + ".LLOGATER VALUES (NEXT VALUE FOR COMMENT_GEN, infollogater???, TRUE, nse com fotreli la habitacio xd)",
                "INSERT INTO " + schema + ".LLOGATER VALUES (NEXT VALUE FOR COMMENT_GEN, infollogater???, TRUE, nse com fotreli la habitacio xd)",
            };
            for (String datum : data) {
                if (stmt.executeUpdate(datum)<=0) {
                    out.println("<span class='error'>Error inserting data: " + datum + "</span>");
                    return;
                }
                out.println("<pre> -> " + datum + "<pre>");
            }
        %>
        <button onclick="window.location='<%=request.getSession().getServletContext().getContextPath()%>'">Go home</button>
    </body>
</html>
